### ISSUE TITLE
Handle files without trailing newline

### ISSUE THREAD

**Issue by RichardSimko** [vvo/concat-files#1]
If you append to files where the first doesn't have a newline at the end of the file, the last line of the first file and the first line of the second file will be on the same line. It would be nice to have an option to handle EOF as a newline.

For example

`file1`

    test
    test2

`file2`

    test3

Will result in

    test
    test2test3

Unless a newline is added at the end of the first file. I would like an option to get the result

    test
    test2
    test3

Without having to change the first file.

**Comment by vvo** [comment]
Can you submit a failing test and a PR maybe? Thanks!

Also there might be more modern modules to do concatenation of files, this one is pretty old :)

**Comment by RichardSimko** [comment]
Thanks for the reply, I ended up switching lib.

**Comment by vvo** [comment]
Can you say which lib you used? So that I can update the readme, cc @RichardSimko

**Comment by RichardSimko** [comment]
I ended up using [concatenate](https://www.npmjs.com/package/concatenate), however it didn't really solve this issue (I just thought it did) and it's not newer than this one. I mainly switched due to the fact that it has a synchronous option.

There really aren't any good libs for file concatenation for node, maybe it can be done easy enough using fs, I haven't put much time into researching that ;)

**Comment by vvo** [comment]
Yes doing it synchronously is easy: fs.writeFileSync ( fs.readFileSync + fs.readFileSync )
