### ISSUE TITLE
Final size

### ISSUE THREAD

**Issue by jonataswalker** [vvo/concat-files#4]
Hey!

Would you accept a PR to show the final file size? We could use [maxmin](https://www.npmjs.com/package/maxmin).

**Comment by vvo** [comment]
Hey hi! I have not been using this module for a LONG time. I guess there are better solutions nowadays to concatenate two files BUT if you want to add a feature, please do.

Can you explain what the API changes could be? Thanks.

**Comment by jonataswalker** [comment]
Yeah, you're right. I've already use https://github.com/szwacz/fs-jetpack and is easy to "concat" files.

Cheers.
